# Generated by Django 5.1.3 on 2024-11-18 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_control', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('clase', models.CharField(blank=True, max_length=50)),
                ('credencial', models.CharField(max_length=20, unique=True)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No especificado', 'No especificado')], default='No especificado', max_length=20)),
                ('semestre', models.IntegerField(default=5)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.carrera')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
    ]
