# Generated by Django 5.1.3 on 2024-11-18 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_remove_estudiante_materia_remove_profesor_materia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='clase',
        ),
        migrations.AddField(
            model_name='clase',
            name='prof',
            field=models.ManyToManyField(related_name='clases', to='catalogos.profesor'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='catalogos.clase'),
        ),
    ]
