# Generated by Django 5.1.3 on 2024-11-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_remove_profesor_clase_clase_prof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='prof',
        ),
        migrations.AddField(
            model_name='profesor',
            name='clases',
            field=models.ManyToManyField(blank=True, related_name='profesores', to='catalogos.clase'),
        ),
    ]
