# Generated by Django 5.1.3 on 2024-11-19 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_remove_profesor_clases_clase_prof_profesor_clase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('asistencia', models.BooleanField()),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.clase')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.estudiante')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.profesor')),
            ],
        ),
    ]
