# Generated by Django 5.1.3 on 2024-11-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_asistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='clase',
        ),
    ]
