# Generated by Django 5.1.3 on 2024-11-17 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0002_rename_nombre_usuario_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='password',
        ),
    ]
