# Generated by Django 5.1.3 on 2024-11-17 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0004_alter_usuario_email_alter_usuario_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='username',
            new_name='nombre',
        ),
    ]
