# Generated by Django 5.1.3 on 2024-11-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0005_rename_username_usuario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('prefiero_no_decirlo', 'Prefiero no decirlo')], default='prefiero_no_decirlo', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(help_text='Máximo 128 caracteres', max_length=128),
        ),
    ]
