# Generated by Django 5.1.3 on 2024-11-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0006_usuario_genero_alter_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usunom',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
