# Generated by Django 5.1.3 on 2024-11-18 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0008_alter_usuario_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='contraseña',
        ),
    ]
