# Generated by Django 5.1.3 on 2024-11-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0009_rename_password_usuario_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('hombre', 'Hombre'), ('Mujer', 'Mujer'), ('otro', 'Otro'), ('prefiero_no_decirlo', 'Prefiero no decirlo')], default='prefiero_no_decirlo', max_length=20),
        ),
    ]
